### ISSUE TITLE
Este tipo da fallo.

### ISSUE THREAD

**Issue by perpifran** [julgonmej/ds1302#16]
https://github.com/julgonmej/ds1302/blob/bccdf14c957a8b3b580336d1c85eeb5a2e8118a1/DS1302.c#L85

**Comment by julgonmej** [comment]
Habrá que cambiarlo por int

**Comment by perpifran** [comment]
estoy de acuerdo mister GI @julgonmej

**Comment by julgonmej** [comment]
Esperemos a la opinion de @CapitanMierder para arreglarlo o no

**Comment by JaiCarCha** [comment]
Por mi bien

**Comment by julgonmej** [comment]
En realidad prefiero irme a comer, WONTFIX
