### ISSUE TITLE
Hay errores en algunas máquinas.

### ISSUE THREAD

**Issue by perpifran** [julgonmej/ds1302#18]
https://github.com/julgonmej/ds1302/blob/fdebfeae4b29eca323651f6d313192dd4fdeb094/suma.c#L6

En algunas máquinas da fallo. Sería bueno usar funciones de ~~match.c~~ math.h

**Comment by JaiCarCha** [comment]
@perpifran va a una academia de inglés pero no se nota

**Comment by perpifran** [comment]
corregido

**Comment by JaiCarCha** [comment]
@perpifran  No existe ningún math.c ¿Que se supone que tengo que hacer?

**Comment by perpifran** [comment]
thats your duty.

**Comment by JaiCarCha** [comment]
OMFG!!!
